In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from losses_metrics import *
from common import *

In [2]:
train = pd.read_csv(f'data/train.csv')
y = train[TARGETS].values
ix = np.where(train.groupby("question_body")["host"].transform("count") == 1)[0]

In [3]:
oofs2 = pd.read_csv('oofs/siamese_bert_2_oofs.csv', index_col=0).values
oofs3 = pd.read_csv('oofs/siamese_bert_3_oofs.csv', index_col=0).values
oofs4 = pd.read_csv('oofs/siamese_bert_4_oofs.csv', index_col=0).values
oofs5 = pd.read_csv('oofs/siamese_bert_5_oofs.csv', index_col=0).values
oofs6 = pd.read_csv('oofs/siamese_bert_6_oofs.csv', index_col=0).values
oofs_ro1 = pd.read_csv('oofs/siamese_roberta_1_comb_oofs.csv', index_col=0).values
oofs_ro2 = pd.read_csv('oofs/siamese_roberta_2_oofs.csv', index_col=0).values
oofs_ro3 = pd.read_csv('oofs/siamese_roberta_3_oofs.csv', index_col=0).values
oofs_xl1 = pd.read_csv('oofs/siamese_xlnet_1_comb_oofs.csv', index_col=0).values
oofs_xl2 = pd.read_csv('oofs/siamese_xlnet_2_comb_oofs.csv', index_col=0).values
oofs_al1 = pd.read_csv('oofs/siamese_albert_1_comb_oofs.csv', index_col=0).values
oofs_use = pd.read_csv('oofs/use_oof.csv').values[:,:N_TARGETS]

In [4]:
get_cvs(oofs_ro2, y, ix)

/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1892: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


SpearmanR
CV                                                0.398317
CV unique rows                                    0.358335
CV ignoring hard targets                          0.421212
CV unique rows ignoring hard targets              0.378551
CV w rounding                                     0.426286
CV unique rows w rounding                         0.398836
CV ignoring hard targets w rounding               0.451178
CV unique rows ignoring hard targets w rounding   0.421945

In [5]:
get_cvs(oofs_use, y, ix)

SpearmanR
CV                                                0.392637
CV unique rows                                    0.355856
CV ignoring hard targets                          0.415201
CV unique rows ignoring hard targets              0.375362
CV w rounding                                     0.421824
CV unique rows w rounding                         0.403783
CV ignoring hard targets w rounding               0.437981
CV unique rows ignoring hard targets w rounding   0.402811

In [6]:
get_cvs(oofs_al1, y, ix)

SpearmanR
CV                                                0.413008
CV unique rows                                    0.378925
CV ignoring hard targets                          0.436447
CV unique rows ignoring hard targets              0.399252
CV w rounding                                     0.441115
CV unique rows w rounding                         0.419050
CV ignoring hard targets w rounding               0.459613
CV unique rows ignoring hard targets w rounding   0.427772

In [7]:
get_cvs(oofs2, y, ix)

SpearmanR
CV                                                0.407278
CV unique rows                                    0.371782
CV ignoring hard targets                          0.431038
CV unique rows ignoring hard targets              0.392546
CV w rounding                                     0.445099
CV unique rows w rounding                         0.435179
CV ignoring hard targets w rounding               0.457188
CV unique rows ignoring hard targets w rounding   0.425629

In [8]:
get_cvs(oofs3, y, ix)

SpearmanR
CV                                                0.410318
CV unique rows                                    0.374227
CV ignoring hard targets                          0.433832
CV unique rows ignoring hard targets              0.394997
CV w rounding                                     0.444981
CV unique rows w rounding                         0.431669
CV ignoring hard targets w rounding               0.459156
CV unique rows ignoring hard targets w rounding   0.428766

In [9]:
get_cvs(oofs4, y, ix)

SpearmanR
CV                                                0.407975
CV unique rows                                    0.372431
CV ignoring hard targets                          0.431877
CV unique rows ignoring hard targets              0.393583
CV w rounding                                     0.448154
CV unique rows w rounding                         0.425383
CV ignoring hard targets w rounding               0.457686
CV unique rows ignoring hard targets w rounding   0.425498

In [10]:
get_cvs(oofs5, y, ix)

SpearmanR
CV                                                0.408816
CV unique rows                                    0.371531
CV ignoring hard targets                          0.432205
CV unique rows ignoring hard targets              0.391879
CV w rounding                                     0.447462
CV unique rows w rounding                         0.427315
CV ignoring hard targets w rounding               0.457939
CV unique rows ignoring hard targets w rounding   0.426188

In [11]:
get_cvs(oofs6, y, ix)

SpearmanR
CV                                                0.410308
CV unique rows                                    0.373700
CV ignoring hard targets                          0.433768
CV unique rows ignoring hard targets              0.394195
CV w rounding                                     0.452310
CV unique rows w rounding                         0.433089
CV ignoring hard targets w rounding               0.460036
CV unique rows ignoring hard targets w rounding   0.427359

In [12]:
opt_ds6, opt_indices6 = optimize_rounding_params(oofs6, y, False)
np.array(opt_ds6), np.array(opt_indices6)

(array([ 8,  4, 16,  8,  4, 16,  8,  4, 16]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 19]))

In [13]:
opt_ds6, opt_indices6 = optimize_rounding_params(oofs6, y, False, ix=ix)
np.array(opt_ds6), np.array(opt_indices6)

(array([ 4,  4, 16,  8,  2,  4,  8,  2,  4, 16, 16, 16, 32]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 16, 19, 21, 23, 26]))

In [14]:
get_cvs(oofs_ro1, y, ix)

SpearmanR
CV                                                0.416249
CV unique rows                                    0.382360
CV ignoring hard targets                          0.440614
CV unique rows ignoring hard targets              0.404309
CV w rounding                                     0.449898
CV unique rows w rounding                         0.428115
CV ignoring hard targets w rounding               0.470601
CV unique rows ignoring hard targets w rounding   0.443194

In [15]:
opt_ds_ro1, opt_indices_ro1 = optimize_rounding_params(oofs_ro1, y, False)
np.array(opt_ds_ro1), np.array(opt_indices_ro1)

(array([ 4,  4, 32,  4,  4,  4,  4,  4, 16, 64]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 16, 19]))

In [16]:
opt_ds_ro1, opt_indices_ro1 = optimize_rounding_params(oofs_ro1, y, False, ix=ix)
np.array(opt_ds_ro1), np.array(opt_indices_ro1)

(array([ 4,  4,  4, 64, 32,  4,  4,  4,  4,  4,  4, 16, 64,  8]),
 array([ 2,  5,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 21]))

In [17]:
get_cvs(oofs_xl1, y, ix)

SpearmanR
CV                                                0.413989
CV unique rows                                    0.376808
CV ignoring hard targets                          0.437868
CV unique rows ignoring hard targets              0.398173
CV w rounding                                     0.448000
CV unique rows w rounding                         0.423921
CV ignoring hard targets w rounding               0.467257
CV unique rows ignoring hard targets w rounding   0.439067

In [18]:
get_cvs(oofs_xl2, y, ix)

SpearmanR
CV                                                0.415561
CV unique rows                                    0.380504
CV ignoring hard targets                          0.439752
CV unique rows ignoring hard targets              0.402323
CV w rounding                                     0.446863
CV unique rows w rounding                         0.431771
CV ignoring hard targets w rounding               0.469367
CV unique rows ignoring hard targets w rounding   0.443250

In [19]:
get_cvs((oofs2+oofs3)/2, y, ix)

SpearmanR
CV                                                0.412118
CV unique rows                                    0.375994
CV ignoring hard targets                          0.435919
CV unique rows ignoring hard targets              0.396939
CV w rounding                                     0.448326
CV unique rows w rounding                         0.431571
CV ignoring hard targets w rounding               0.462058
CV unique rows ignoring hard targets w rounding   0.430824

In [20]:
get_cvs((oofs3+oofs5)/2, y, ix)

SpearmanR
CV                                                0.413033
CV unique rows                                    0.376192
CV ignoring hard targets                          0.436685
CV unique rows ignoring hard targets              0.396945
CV w rounding                                     0.455283
CV unique rows w rounding                         0.434801
CV ignoring hard targets w rounding               0.463314
CV unique rows ignoring hard targets w rounding   0.429981

In [21]:
get_cvs((oofs2+oofs5)/2, y, ix)

SpearmanR
CV                                                0.412006
CV unique rows                                    0.375443
CV ignoring hard targets                          0.435828
CV unique rows ignoring hard targets              0.396227
CV w rounding                                     0.453626
CV unique rows w rounding                         0.432675
CV ignoring hard targets w rounding               0.462489
CV unique rows ignoring hard targets w rounding   0.428766

In [22]:
get_cvs((oofs3+oofs6)/2, y, ix)

SpearmanR
CV                                                0.412990
CV unique rows                                    0.376564
CV ignoring hard targets                          0.436623
CV unique rows ignoring hard targets              0.397339
CV w rounding                                     0.455267
CV unique rows w rounding                         0.434622
CV ignoring hard targets w rounding               0.463397
CV unique rows ignoring hard targets w rounding   0.429726

In [23]:
get_cvs((oofs_ro1+oofs_xl1)/2, y, ix)

SpearmanR
CV                                                0.423084
CV unique rows                                    0.387084
CV ignoring hard targets                          0.447699
CV unique rows ignoring hard targets              0.409294
CV w rounding                                     0.459490
CV unique rows w rounding                         0.437245
CV ignoring hard targets w rounding               0.478693
CV unique rows ignoring hard targets w rounding   0.450969

In [24]:
get_cvs((oofs_ro1+oofs_xl2)/2, y, ix)

SpearmanR
CV                                                0.423610
CV unique rows                                    0.388907
CV ignoring hard targets                          0.448323
CV unique rows ignoring hard targets              0.411274
CV w rounding                                     0.459002
CV unique rows w rounding                         0.434901
CV ignoring hard targets w rounding               0.479233
CV unique rows ignoring hard targets w rounding   0.449830

In [25]:
get_cvs((oofs_xl1+oofs6)/2, y, ix)

SpearmanR
CV                                                0.422256
CV unique rows                                    0.384862
CV ignoring hard targets                          0.446461
CV unique rows ignoring hard targets              0.406397
CV w rounding                                     0.462555
CV unique rows w rounding                         0.442123
CV ignoring hard targets w rounding               0.475676
CV unique rows ignoring hard targets w rounding   0.446994

In [26]:
get_cvs((oofs_ro1+oofs6)/2, y, ix)

SpearmanR
CV                                                0.423435
CV unique rows                                    0.387722
CV ignoring hard targets                          0.447835
CV unique rows ignoring hard targets              0.409526
CV w rounding                                     0.463246
CV unique rows w rounding                         0.442005
CV ignoring hard targets w rounding               0.475874
CV unique rows ignoring hard targets w rounding   0.446068

In [27]:
get_cvs((oofs_ro1+oofs_xl1+oofs6)/3, y, ix)

SpearmanR
CV                                                0.426310
CV unique rows                                    0.389911
CV ignoring hard targets                          0.450891
CV unique rows ignoring hard targets              0.411984
CV w rounding                                     0.467891
CV unique rows w rounding                         0.448617
CV ignoring hard targets w rounding               0.480947
CV unique rows ignoring hard targets w rounding   0.450783

In [28]:
opt_ds_ens, opt_indices_ens = optimize_rounding_params((oofs_ro1+oofs_xl1+oofs6)/3, y, False)
np.array(opt_ds_ens), np.array(opt_indices_ens)

(array([ 4,  4, 32,  8,  4,  4,  8,  4,  8, 32, 16, 32]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 16, 19, 21, 24]))

In [29]:
opt_ds_ens, opt_indices_ens = optimize_rounding_params((oofs_ro1+oofs_xl1+oofs6)/3, y, False, ix=ix)
np.array(opt_ds_ens), np.array(opt_indices_ens)

(array([ 4, 16,  4, 32, 16,  8,  2,  4,  4,  4,  4, 32, 32,  8,  4, 32]),
 array([ 2,  3,  5,  6,  9, 11, 12, 13, 14, 15, 16, 19, 22, 24, 26, 27]))

In [30]:
get_cvs((oofs_ro1+oofs_xl2+oofs6)/3, y, ix)

SpearmanR
CV                                                0.426625
CV unique rows                                    0.391047
CV ignoring hard targets                          0.451229
CV unique rows ignoring hard targets              0.413195
CV w rounding                                     0.467387
CV unique rows w rounding                         0.446829
CV ignoring hard targets w rounding               0.480662
CV unique rows ignoring hard targets w rounding   0.452020

In [31]:
get_cvs((oofs_ro1+oofs_xl2+oofs6+oofs_al1)/4, y, ix)

SpearmanR
CV                                                0.429347
CV unique rows                                    0.393868
CV ignoring hard targets                          0.454001
CV unique rows ignoring hard targets              0.415883
CV w rounding                                     0.468289
CV unique rows w rounding                         0.447073
CV ignoring hard targets w rounding               0.482600
CV unique rows ignoring hard targets w rounding   0.452884

	SpearmanR
CV	0.429112
CV unique rows	0.393685
CV ignoring hard targets	0.453767
CV unique rows ignoring hard targets	0.415706
CV w rounding	0.466640
CV unique rows w rounding	0.446133
CV ignoring hard targets w rounding	0.481780
CV unique rows ignoring hard targets w rounding	0.452305

In [32]:
get_cvs((oofs_ro1+oofs_xl2+oofs6+oofs_al1+oofs_use)/5, y, ix)

SpearmanR
CV                                                0.430661
CV unique rows                                    0.395234
CV ignoring hard targets                          0.455351
CV unique rows ignoring hard targets              0.417092
CV w rounding                                     0.467419
CV unique rows w rounding                         0.447997
CV ignoring hard targets w rounding               0.483268
CV unique rows ignoring hard targets w rounding   0.454673

In [33]:
get_cvs((oofs_ro1+oofs_xl1+oofs6+oofs_al1+oofs_use)/5, y, ix)

SpearmanR
CV                                                0.430611
CV unique rows                                    0.394650
CV ignoring hard targets                          0.455266
CV unique rows ignoring hard targets              0.416456
CV w rounding                                     0.470380
CV unique rows w rounding                         0.450330
CV ignoring hard targets w rounding               0.483720
CV unique rows ignoring hard targets w rounding   0.455412

In [34]:
get_cvs((oofs_ro1+oofs_xl2+oofs6+oofs_al1+oofs_use+oofs_ro2)/6, y, ix)

SpearmanR
CV                                                0.430674
CV unique rows                                    0.394819
CV ignoring hard targets                          0.455369
CV unique rows ignoring hard targets              0.416670
CV w rounding                                     0.468620
CV unique rows w rounding                         0.449144
CV ignoring hard targets w rounding               0.484771
CV unique rows ignoring hard targets w rounding   0.455954

In [35]:
corrs = []
oofs = [('BERT', oofs6), ('RoBERTa1', oofs_ro1), ('RoBERTa2', oofs_ro2), ('RoBERTa3', oofs_ro3), 
        ('XLNet1', oofs_xl1), ('XLNet2', oofs_xl2), 
        ('ALBERT', oofs_al1), ('USE', oofs_use)]
for c in range(N_TARGETS):
    corr = spearmanr(np.vstack([oof[:,c] for _, oof in oofs]).T)[0]
    corrs_col = []
    for i in range(len(oofs)):
        for j in range(i+1, len(oofs)):
            corrs_col.append(corr[i,j])
    corrs.append(corrs_col)
    
cols = []
for i, (name1, _) in enumerate(oofs):
    for j, (name2, _) in enumerate(oofs[i+1:]):
        cols.append(f'{name1}-{name2}')

In [36]:
np.vstack([oof[:,c] for _, oof in oofs]).shape

(8, 6079)

In [37]:
corrs_df = pd.DataFrame(corrs, index=TARGETS, columns=cols)
corrs_df

BERT-RoBERTa1  BERT-RoBERTa2  \
question_asker_intent_understanding         0.890034       0.875108   
question_body_critical                      0.856560       0.835685   
question_conversational                     0.873000       0.802866   
question_expect_short_answer                0.837686       0.785528   
question_fact_seeking                       0.865800       0.812202   
question_has_commonly_accepted_answer       0.865777       0.817857   
question_interestingness_others             0.900911       0.889399   
question_interestingness_self               0.896772       0.876219   
question_multi_intent                       0.873396       0.807620   
question_not_really_a_question              0.744657       0.604016   
question_opinion_seeking                    0.886192       0.858889   
question_type_choice                        0.926038       0.877584   
question_type_compare                       0.858403       0.794196   
question_type_consequence                   0.837351       0.790020   
question_type_definition                    0.813672       0.717498   
question_type_entity                        0.831026       0.782551   
question_type_instructions                  0.959585       0.942189   
question_type_procedure                     0.880509       0.840077   
question_type_reason_explanation            0.934359       0.911903   
question_type_spelling                      0.655307       0.543313   
question_well_written                       0.874296       0.848214   
answer_helpful                              0.788714       0.625833   
answer_level_of_information                 0.864996       0.719019   
answer_plausible                            0.753047       0.575258   
answer_relevance                            0.757064       0.603389   
answer_satisfaction                         0.803540       0.674406   
answer_type_instructions                    0.961803       0.932965   
answer_type_procedure                       0.878886       0.800799   
answer_type_reason_explanation              0.943060       0.882934   
answer_well_written                         0.735457       0.599680   

                                       BERT-RoBERTa3  BERT-XLNet1  \
question_asker_intent_understanding         0.883005     0.887435   
question_body_critical                      0.885217     0.868631   
question_conversational                     0.856050     0.882512   
question_expect_short_answer                0.792741     0.825072   
question_fact_seeking                       0.822492     0.854729   
question_has_commonly_accepted_answer       0.835255     0.869714   
question_interestingness_others             0.881591     0.893525   
question_interestingness_self               0.888074     0.898871   
question_multi_intent                       0.875710     0.884589   
question_not_really_a_question              0.667295     0.739720   
question_opinion_seeking                    0.856883     0.879223   
question_type_choice                        0.924267     0.933725   
question_type_compare                       0.833425     0.863477   
question_type_consequence                   0.807845     0.828693   
question_type_definition                    0.799737     0.822941   
question_type_entity                        0.831521     0.839155   
question_type_instructions                  0.952556     0.960540   
question_type_procedure                     0.843946     0.870519   
question_type_reason_explanation            0.921515     0.931377   
question_type_spelling                      0.591900     0.695330   
question_well_written                       0.873273     0.884595   
answer_helpful                              0.733892     0.775847   
answer_level_of_information                 0.791787     0.857524   
answer_plausible                            0.694662     0.736873   
answer_relevance                            0.689805     0.737799   
answer_satisfaction                        

In [38]:
corrs_df.mean()

BERT-RoBERTa1        0.851597
BERT-RoBERTa2        0.780907
BERT-RoBERTa3        0.820836
BERT-XLNet1          0.850852
BERT-XLNet2          0.856485
BERT-ALBERT          0.854210
BERT-USE             0.777238
RoBERTa1-RoBERTa2    0.820914
RoBERTa1-RoBERTa3    0.864376
RoBERTa1-XLNet1      0.875620
RoBERTa1-XLNet2      0.880554
RoBERTa1-ALBERT      0.838838
RoBERTa1-USE         0.775906
RoBERTa2-RoBERTa3    0.811569
RoBERTa2-XLNet1      0.790049
RoBERTa2-XLNet2      0.798629
RoBERTa2-ALBERT      0.778384
RoBERTa2-USE         0.756654
RoBERTa3-XLNet1      0.833973
RoBERTa3-XLNet2      0.841953
RoBERTa3-ALBERT      0.821987
RoBERTa3-USE         0.761406
XLNet1-XLNet2        0.948899
XLNet1-ALBERT        0.839471
XLNet1-USE           0.770530
XLNet2-ALBERT        0.845529
XLNet2-USE           0.779677
ALBERT-USE           0.772702
dtype: float64

In [39]:
corr_mat_df = np.eye(len(oofs))
for i, (name1, _) in enumerate(oofs):
    for j, (name2, _) in enumerate(oofs[i+1:]):
        corr_mat_df[i,i+j+1] = corrs_df.mean()[f'{name1}-{name2}']
corr_mat_df = pd.DataFrame(corr_mat_df, index=[n for n, _ in oofs], columns=[n for n, _ in oofs])
corr_mat_df

BERT  RoBERTa1  RoBERTa2  RoBERTa3    XLNet1    XLNet2    ALBERT  \
BERT       1.0  0.851597  0.780907  0.820836  0.850852  0.856485  0.854210   
RoBERTa1   0.0  1.000000  0.820914  0.864376  0.875620  0.880554  0.838838   
RoBERTa2   0.0  0.000000  1.000000  0.811569  0.790049  0.798629  0.778384   
RoBERTa3   0.0  0.000000  0.000000  1.000000  0.833973  0.841953  0.821987   
XLNet1     0.0  0.000000  0.000000  0.000000  1.000000  0.948899  0.839471   
XLNet2     0.0  0.000000  0.000000  0.000000  0.000000  1.000000  0.845529   
ALBERT     0.0  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000   
USE        0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

               USE  
BERT      0.777238  
RoBERTa1  0.775906  
RoBERTa2  0.756654  
RoBERTa3  0.761406  
XLNet1    0.770530  
XLNet2    0.779677  
ALBERT    0.772702  
USE       1.000000