In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from losses_metrics import *
from common import *

In [2]:
train = pd.read_csv(f'data/train.csv')
y = train[TARGETS].values
ix = np.where(train.groupby("question_body")["host"].transform("count") == 1)[0]

In [3]:
oofs2 = pd.read_csv('oofs/siamese_bert_2_oofs.csv', index_col=0).values
oofs3 = pd.read_csv('oofs/siamese_bert_3_oofs.csv', index_col=0).values
oofs4 = pd.read_csv('oofs/siamese_bert_4_oofs.csv', index_col=0).values
oofs5 = pd.read_csv('oofs/siamese_bert_5_oofs.csv', index_col=0).values

In [4]:
get_cvs(oofs2, y, ix)

/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1892: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


SpearmanR
CV                                                0.407278
CV unique rows                                    0.371782
CV ignoring hard targets                          0.431038
CV unique rows ignoring hard targets              0.392546
CV w rounding                                     0.448776
CV unique rows w rounding                         0.432710
CV ignoring hard targets w rounding               0.457380
CV unique rows ignoring hard targets w rounding   0.423055

In [5]:
get_cvs(oofs3, y, ix)

SpearmanR
CV                                                0.410318
CV unique rows                                    0.374227
CV ignoring hard targets                          0.433832
CV unique rows ignoring hard targets              0.394997
CV w rounding                                     0.443676
CV unique rows w rounding                         0.428869
CV ignoring hard targets w rounding               0.458653
CV unique rows ignoring hard targets w rounding   0.427826

In [6]:
get_cvs(oofs4, y, ix)

SpearmanR
CV                                                0.410915
CV unique rows                                    0.374687
CV ignoring hard targets                          0.434463
CV unique rows ignoring hard targets              0.395569
CV w rounding                                     0.449694
CV unique rows w rounding                         0.421206
CV ignoring hard targets w rounding               0.460004
CV unique rows ignoring hard targets w rounding   0.425556

In [7]:
get_cvs(oofs5, y, ix)

SpearmanR
CV                                                0.408816
CV unique rows                                    0.371531
CV ignoring hard targets                          0.432205
CV unique rows ignoring hard targets              0.391879
CV w rounding                                     0.451041
CV unique rows w rounding                         0.428981
CV ignoring hard targets w rounding               0.458007
CV unique rows ignoring hard targets w rounding   0.425146

In [8]:
get_cvs((oofs2+oofs3)/2, y, ix)

SpearmanR
CV                                                0.412118
CV unique rows                                    0.375994
CV ignoring hard targets                          0.435919
CV unique rows ignoring hard targets              0.396939
CV w rounding                                     0.447414
CV unique rows w rounding                         0.432944
CV ignoring hard targets w rounding               0.461039
CV unique rows ignoring hard targets w rounding   0.427675

In [9]:
get_cvs((oofs3+oofs5)/2, y, ix)

SpearmanR
CV                                                0.413033
CV unique rows                                    0.376192
CV ignoring hard targets                          0.436685
CV unique rows ignoring hard targets              0.396945
CV w rounding                                     0.453826
CV unique rows w rounding                         0.433865
CV ignoring hard targets w rounding               0.462182
CV unique rows ignoring hard targets w rounding   0.428614

In [14]:
get_cvs((oofs2+oofs5)/2, y, ix)

SpearmanR
CV                                                0.412006
CV unique rows                                    0.375443
CV ignoring hard targets                          0.435828
CV unique rows ignoring hard targets              0.396227
CV w rounding                                     0.453693
CV unique rows w rounding                         0.431880
CV ignoring hard targets w rounding               0.462048
CV unique rows ignoring hard targets w rounding   0.428392

In [12]:
get_cvs((oofs2+oofs3+oofs4+oofs5)/4, y, ix)

SpearmanR
CV                                                0.414650
CV unique rows                                    0.378031
CV ignoring hard targets                          0.438476
CV unique rows ignoring hard targets              0.399053
CV w rounding                                     0.455960
CV unique rows w rounding                         0.435108
CV ignoring hard targets w rounding               0.464166
CV unique rows ignoring hard targets w rounding   0.429039

In [38]:
from scipy.stats import rankdata
def get_rank_oofs(oofs):
    rank_oofs = np.zeros_like(oofs)
    for i in range(N_TARGETS): rank_oofs[:,i] = rankdata(oofs[:,i])
    return rank_oofs

In [51]:
rounded_oofs3 = optimized_ahmet_round(oofs3, y, verbose=False)
rounded_oofs5 = optimized_ahmet_round(oofs5, y, verbose=False)

/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1892: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


In [52]:
rank_oofs3 = get_rank_oofs(oofs3)
rank_oofs5 = get_rank_oofs(oofs5)

mins = ((oofs3+oofs5)/2).min(axis=0)
maxs = ((oofs3+oofs5)/2).min(axis=0)

rank_oofs35 = MinMaxScaler().fit_transform((rank_oofs3 + rank_oofs5)/2)
# rank_oofs35 = rank_oofs35 * (maxs - mins) + mins

get_cvs(rank_oofs35, y, ix)

SpearmanR
CV                                                0.413050
CV unique rows                                    0.376224
CV ignoring hard targets                          0.436686
CV unique rows ignoring hard targets              0.396950
CV w rounding                                     0.413207
CV unique rows w rounding                         0.376705
CV ignoring hard targets w rounding               0.436852
CV unique rows ignoring hard targets w rounding   0.397465

In [54]:
rank_oofs3 = get_rank_oofs(rounded_oofs3)
rank_oofs5 = get_rank_oofs(rounded_oofs5)

mins = ((oofs3+oofs5)/2).min(axis=0)
maxs = ((oofs3+oofs5)/2).min(axis=0)

rank_oofs35 = MinMaxScaler().fit_transform((rank_oofs3 + rank_oofs5)/2)
# rank_oofs35 = rank_oofs35 * (maxs - mins) + mins

get_cvs(rank_oofs35, y, ix)

SpearmanR
CV                                                0.447335
CV unique rows                                    0.417834
CV ignoring hard targets                          0.460805
CV unique rows ignoring hard targets              0.424177
CV w rounding                                     0.447450
CV unique rows w rounding                         0.418436
CV ignoring hard targets w rounding               0.460925
CV unique rows ignoring hard targets w rounding   0.424814

In [56]:
rank_oofs3[:,:5]

array([[4807.5, 4873.5, 5444.5, 2074. ,  750. ],
       [5656. , 5472. , 2615. , 1685. , 5660. ],
       [2213. ,  979. , 2615. , 5029. , 3891.5],
       ...,
       [1462.5, 1314. , 2615. , 3366. , 2815. ],
       [4449. , 2805.5, 5777. ,  281. ,  250. ],
       [3138.5, 4799.5, 2615. ,  135. , 5660. ]])

In [57]:
rank_oofs5[:,:5]

array([[3966. , 4328.5, 5334.5, 1185.5,  839.5],
       [4891. , 4954.5, 2322.5,  858. , 5260. ],
       [2959.5, 1512.5, 2322.5, 4792. , 2837.5],
       ...,
       [1529. , 1597. , 2322.5, 4520.5, 2837.5],
       [4770.5, 3917. , 6006. ,  101. ,  291.5],
       [4204.5, 5282.5, 4918.5,   70.5, 5260. ]])

In [59]:
MinMaxScaler().fit_transform((rank_oofs3 + rank_oofs5)/2)[:,:5]

array([[0.72162318, 0.75668218, 0.81075642, 0.26762418, 0.13517966],
       [0.86760227, 0.85754293, 0.        , 0.20865056, 0.96607151],
       [0.42522018, 0.20394547, 0.        , 0.80768756, 0.5928581 ],
       ...,
       [0.24569923, 0.23849924, 0.        , 0.6484629 , 0.49699452],
       [0.75833402, 0.55244842, 0.95010409, 0.03078316, 0.04185405],
       [0.60387686, 0.82916684, 0.36030534, 0.01625581, 0.96607151]])