In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from losses_metrics import *
from common import *

In [2]:
train = pd.read_csv(f'data/train.csv')
y = train[TARGETS].values
ix = np.where(train.groupby("question_body")["host"].transform("count") == 1)[0]

In [62]:
oofs2 = pd.read_csv('oofs/siamese_bert_2_oofs.csv', index_col=0).values
oofs3 = pd.read_csv('oofs/siamese_bert_3_oofs.csv', index_col=0).values
oofs4 = pd.read_csv('oofs/siamese_bert_4_oofs.csv', index_col=0).values
oofs5 = pd.read_csv('oofs/siamese_bert_5_oofs.csv', index_col=0).values
oofs6 = pd.read_csv('oofs/siamese_bert_6_oofs.csv', index_col=0).values
oofs_ro1 = pd.read_csv('oofs/siamese_roberta_1_comb_oofs.csv', index_col=0).values
oofs_xl1 = pd.read_csv('oofs/siamese_xlnet_1_comb_oofs.csv', index_col=0).values
oofs_xl2 = pd.read_csv('oofs/siamese_xlnet_2_comb_oofs.csv', index_col=0).values
oofs_al1 = pd.read_csv('oofs/siamese_albert_1_oofs.csv', index_col=0).values

In [63]:
get_cvs(oofs_al1, y, ix)

/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1892: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


SpearmanR
CV                                                0.403478
CV unique rows                                    0.367723
CV ignoring hard targets                          0.426487
CV unique rows ignoring hard targets              0.388003
CV w rounding                                     0.427640
CV unique rows w rounding                         0.407768
CV ignoring hard targets w rounding               0.447124
CV unique rows ignoring hard targets w rounding   0.412796

In [4]:
get_cvs(oofs2, y, ix)

/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1892: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


SpearmanR
CV                                                0.407278
CV unique rows                                    0.371782
CV ignoring hard targets                          0.431038
CV unique rows ignoring hard targets              0.392546
CV w rounding                                     0.445099
CV unique rows w rounding                         0.434939
CV ignoring hard targets w rounding               0.457188
CV unique rows ignoring hard targets w rounding   0.425372

In [5]:
get_cvs(oofs3, y, ix)

SpearmanR
CV                                                0.410318
CV unique rows                                    0.374227
CV ignoring hard targets                          0.433832
CV unique rows ignoring hard targets              0.394997
CV w rounding                                     0.444981
CV unique rows w rounding                         0.431170
CV ignoring hard targets w rounding               0.459156
CV unique rows ignoring hard targets w rounding   0.428232

In [6]:
get_cvs(oofs4, y, ix)

SpearmanR
CV                                                0.407975
CV unique rows                                    0.372431
CV ignoring hard targets                          0.431877
CV unique rows ignoring hard targets              0.393583
CV w rounding                                     0.448154
CV unique rows w rounding                         0.424980
CV ignoring hard targets w rounding               0.457686
CV unique rows ignoring hard targets w rounding   0.425066

In [7]:
get_cvs(oofs5, y, ix)

SpearmanR
CV                                                0.408816
CV unique rows                                    0.371531
CV ignoring hard targets                          0.432205
CV unique rows ignoring hard targets              0.391879
CV w rounding                                     0.447431
CV unique rows w rounding                         0.426379
CV ignoring hard targets w rounding               0.457907
CV unique rows ignoring hard targets w rounding   0.425185

In [8]:
get_cvs(oofs6, y, ix)

SpearmanR
CV                                                0.410308
CV unique rows                                    0.373700
CV ignoring hard targets                          0.433768
CV unique rows ignoring hard targets              0.394195
CV w rounding                                     0.452310
CV unique rows w rounding                         0.432906
CV ignoring hard targets w rounding               0.460036
CV unique rows ignoring hard targets w rounding   0.427164

In [9]:
opt_ds6, opt_indices6 = optimize_rounding_params(oofs6, y, False)
np.array(opt_ds6), np.array(opt_indices6)

(array([ 8,  4, 16,  8,  4, 16,  8,  4, 16]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 19]))

In [10]:
opt_ds6, opt_indices6 = optimize_rounding_params(oofs6, y, False, ix=ix)
np.array(opt_ds6), np.array(opt_indices6)

(array([ 4,  4, 16,  8,  4,  4,  8,  4,  4, 16, 16, 16, 32]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 16, 19, 21, 23, 26]))

In [11]:
get_cvs(oofs_ro1, y, ix)

SpearmanR
CV                                                0.416249
CV unique rows                                    0.382360
CV ignoring hard targets                          0.440614
CV unique rows ignoring hard targets              0.404309
CV w rounding                                     0.449898
CV unique rows w rounding                         0.428115
CV ignoring hard targets w rounding               0.470601
CV unique rows ignoring hard targets w rounding   0.443194

In [12]:
opt_ds_ro1, opt_indices_ro1 = optimize_rounding_params(oofs_ro1, y, False)
np.array(opt_ds_ro1), np.array(opt_indices_ro1)

(array([ 4,  4, 32,  4,  4,  4,  4,  4, 16, 64]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 16, 19]))

In [13]:
opt_ds_ro1, opt_indices_ro1 = optimize_rounding_params(oofs_ro1, y, False, ix=ix)
np.array(opt_ds_ro1), np.array(opt_indices_ro1)

(array([ 4,  4,  4, 64, 32,  4,  4,  4,  4,  4,  4, 16, 64,  8]),
 array([ 2,  5,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 21]))

In [14]:
get_cvs(oofs_xl1, y, ix)

SpearmanR
CV                                                0.413989
CV unique rows                                    0.376808
CV ignoring hard targets                          0.437868
CV unique rows ignoring hard targets              0.398173
CV w rounding                                     0.448000
CV unique rows w rounding                         0.421965
CV ignoring hard targets w rounding               0.467257
CV unique rows ignoring hard targets w rounding   0.436972

In [15]:
get_cvs(oofs_xl2, y, ix)

SpearmanR
CV                                                0.415561
CV unique rows                                    0.380504
CV ignoring hard targets                          0.439752
CV unique rows ignoring hard targets              0.402323
CV w rounding                                     0.446863
CV unique rows w rounding                         0.431666
CV ignoring hard targets w rounding               0.469367
CV unique rows ignoring hard targets w rounding   0.443137

In [16]:
get_cvs((oofs2+oofs3)/2, y, ix)

SpearmanR
CV                                                0.412118
CV unique rows                                    0.375994
CV ignoring hard targets                          0.435919
CV unique rows ignoring hard targets              0.396939
CV w rounding                                     0.448326
CV unique rows w rounding                         0.430840
CV ignoring hard targets w rounding               0.462058
CV unique rows ignoring hard targets w rounding   0.430041

In [17]:
get_cvs((oofs3+oofs5)/2, y, ix)

SpearmanR
CV                                                0.413033
CV unique rows                                    0.376192
CV ignoring hard targets                          0.436685
CV unique rows ignoring hard targets              0.396945
CV w rounding                                     0.455283
CV unique rows w rounding                         0.434752
CV ignoring hard targets w rounding               0.463314
CV unique rows ignoring hard targets w rounding   0.429928

In [18]:
get_cvs((oofs2+oofs5)/2, y, ix)

SpearmanR
CV                                                0.412006
CV unique rows                                    0.375443
CV ignoring hard targets                          0.435828
CV unique rows ignoring hard targets              0.396227
CV w rounding                                     0.453626
CV unique rows w rounding                         0.432560
CV ignoring hard targets w rounding               0.462489
CV unique rows ignoring hard targets w rounding   0.428642

In [19]:
get_cvs((oofs3+oofs6)/2, y, ix)

SpearmanR
CV                                                0.412990
CV unique rows                                    0.376564
CV ignoring hard targets                          0.436623
CV unique rows ignoring hard targets              0.397339
CV w rounding                                     0.455267
CV unique rows w rounding                         0.434622
CV ignoring hard targets w rounding               0.463397
CV unique rows ignoring hard targets w rounding   0.429726

In [20]:
get_cvs((oofs_ro1+oofs_xl1)/2, y, ix)

SpearmanR
CV                                                0.423084
CV unique rows                                    0.387084
CV ignoring hard targets                          0.447699
CV unique rows ignoring hard targets              0.409294
CV w rounding                                     0.459490
CV unique rows w rounding                         0.436044
CV ignoring hard targets w rounding               0.478693
CV unique rows ignoring hard targets w rounding   0.449683

In [21]:
get_cvs((oofs_ro1+oofs_xl2)/2, y, ix)

SpearmanR
CV                                                0.423610
CV unique rows                                    0.388907
CV ignoring hard targets                          0.448323
CV unique rows ignoring hard targets              0.411274
CV w rounding                                     0.459002
CV unique rows w rounding                         0.434675
CV ignoring hard targets w rounding               0.479233
CV unique rows ignoring hard targets w rounding   0.449588

In [22]:
get_cvs((oofs_xl1+oofs6)/2, y, ix)

SpearmanR
CV                                                0.422256
CV unique rows                                    0.384862
CV ignoring hard targets                          0.446461
CV unique rows ignoring hard targets              0.406397
CV w rounding                                     0.462555
CV unique rows w rounding                         0.442023
CV ignoring hard targets w rounding               0.475676
CV unique rows ignoring hard targets w rounding   0.446887

In [23]:
get_cvs((oofs_ro1+oofs6)/2, y, ix)

SpearmanR
CV                                                0.423435
CV unique rows                                    0.387722
CV ignoring hard targets                          0.447835
CV unique rows ignoring hard targets              0.409526
CV w rounding                                     0.463246
CV unique rows w rounding                         0.441932
CV ignoring hard targets w rounding               0.475874
CV unique rows ignoring hard targets w rounding   0.445989

In [24]:
get_cvs((oofs_ro1+oofs_xl1+oofs6)/3, y, ix)

SpearmanR
CV                                                0.426310
CV unique rows                                    0.389911
CV ignoring hard targets                          0.450891
CV unique rows ignoring hard targets              0.411984
CV w rounding                                     0.467891
CV unique rows w rounding                         0.448483
CV ignoring hard targets w rounding               0.480947
CV unique rows ignoring hard targets w rounding   0.450640

In [25]:
opt_ds_ens, opt_indices_ens = optimize_rounding_params((oofs_ro1+oofs_xl1+oofs6)/3, y, False)
np.array(opt_ds_ens), np.array(opt_indices_ens)

(array([ 4,  4, 32,  8,  4,  4,  8,  4,  8, 32, 16, 32]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 16, 19, 21, 24]))

In [26]:
opt_ds_ens, opt_indices_ens = optimize_rounding_params((oofs_ro1+oofs_xl1+oofs6)/3, y, False, ix=ix)
np.array(opt_ds_ens), np.array(opt_indices_ens)

(array([ 4, 16,  4, 32, 16,  8,  4,  4,  4,  4,  4, 32, 32,  8,  4, 32]),
 array([ 2,  3,  5,  6,  9, 11, 12, 13, 14, 15, 16, 19, 22, 24, 26, 27]))

In [27]:
get_cvs((oofs_ro1+oofs_xl2+oofs6)/3, y, ix)

SpearmanR
CV                                                0.426625
CV unique rows                                    0.391047
CV ignoring hard targets                          0.451229
CV unique rows ignoring hard targets              0.413195
CV w rounding                                     0.467387
CV unique rows w rounding                         0.446829
CV ignoring hard targets w rounding               0.480662
CV unique rows ignoring hard targets w rounding   0.452020

In [28]:
get_cvs((oofs2+oofs3+oofs4+oofs5+oofs6+oofs_xl1+4*oofs_ro1)/10, y, ix)

SpearmanR
CV                                                0.425916
CV unique rows                                    0.389904
CV ignoring hard targets                          0.450572
CV unique rows ignoring hard targets              0.412018
CV w rounding                                     0.467726
CV unique rows w rounding                         0.449817
CV ignoring hard targets w rounding               0.479619
CV unique rows ignoring hard targets w rounding   0.450425

In [29]:
from scipy.stats import rankdata
def get_rank_oofs(oofs):
    rank_oofs = np.zeros_like(oofs)
    for i in range(N_TARGETS): rank_oofs[:,i] = rankdata(oofs[:,i])
    return rank_oofs

In [30]:
rounded_oofs3 = optimized_ahmet_round(oofs3, y, verbose=False)
rounded_oofs5 = optimized_ahmet_round(oofs5, y, verbose=False)

In [31]:
rank_oofs3 = get_rank_oofs(oofs3)
rank_oofs5 = get_rank_oofs(oofs5)

mins = ((oofs3+oofs5)/2).min(axis=0)
maxs = ((oofs3+oofs5)/2).min(axis=0)

rank_oofs35 = MinMaxScaler().fit_transform((rank_oofs3 + rank_oofs5)/2)
# rank_oofs35 = rank_oofs35 * (maxs - mins) + mins

get_cvs(rank_oofs35, y, ix)

SpearmanR
CV                                                0.413050
CV unique rows                                    0.376224
CV ignoring hard targets                          0.436686
CV unique rows ignoring hard targets              0.396950
CV w rounding                                     0.413050
CV unique rows w rounding                         0.376224
CV ignoring hard targets w rounding               0.436686
CV unique rows ignoring hard targets w rounding   0.396950

In [32]:
rank_oofs3 = get_rank_oofs(rounded_oofs3)
rank_oofs5 = get_rank_oofs(rounded_oofs5)

mins = ((oofs3+oofs5)/2).min(axis=0)
maxs = ((oofs3+oofs5)/2).min(axis=0)

rank_oofs35 = MinMaxScaler().fit_transform((rank_oofs3 + rank_oofs5)/2)
# rank_oofs35 = rank_oofs35 * (maxs - mins) + mins

get_cvs(rank_oofs35, y, ix)

SpearmanR
CV                                                0.447501
CV unique rows                                    0.420814
CV ignoring hard targets                          0.462049
CV unique rows ignoring hard targets              0.425230
CV w rounding                                     0.447501
CV unique rows w rounding                         0.420814
CV ignoring hard targets w rounding               0.462049
CV unique rows ignoring hard targets w rounding   0.425230

In [33]:
rank_oofs3[:,:5]

array([[4779. , 4855. , 5501.5, 2074. ,  738. ],
       [5652. , 5448. , 2444.5, 1685. , 5624. ],
       [2196. , 1023. , 2444.5, 5029. , 3672. ],
       ...,
       [1448. , 1299. , 2444.5, 3366. , 2907. ],
       [4431. , 2815. , 5846. ,  281. ,  242. ],
       [3103. , 4769. , 2444.5,  135. , 5615. ]])

In [34]:
rank_oofs5[:,:5]

array([[3982., 4341., 5095., 1156., 1194.],
       [4829., 4982., 2419.,  827., 5377.],
       [2985., 1520., 2419., 4774., 4016.],
       ...,
       [1566., 1603., 2419., 4464., 4129.],
       [4800., 3916., 5949.,   97.,  319.],
       [4219., 5286., 2419.,   68., 5563.]])

In [35]:
MinMaxScaler().fit_transform((rank_oofs3 + rank_oofs5)/2)[:,:5]

array([[0.72065844, 0.7562783 , 0.78939759, 0.26520701, 0.15856167],
       [0.86222222, 0.8578839 , 0.        , 0.2061075 , 0.90479717],
       [0.42600823, 0.20848086, 0.        , 0.8062392 , 0.63218958],
       ...,
       [0.24765432, 0.23804035, 0.        , 0.643839  , 0.57854028],
       [0.75934156, 0.55331412, 0.95442341, 0.03045518, 0.04575002],
       [0.60222222, 0.827007  , 0.        , 0.0160507 , 0.91936147]])

In [64]:
corrs = []
for i in range(N_TARGETS):
    corr = spearmanr(np.vstack((oofs6[:,i], oofs_ro1[:,i], oofs_xl2[:,i])).T)[0]
    corrs.append((corr[0,1], corr[0,2], corr[1,2]))

In [65]:
corrs_df = pd.DataFrame(corrs, index=TARGETS, columns=['BERT-RoBERTa', 'BERT-XLNet', 'RoBERTa-XLNet'])
corrs_df

BERT-RoBERTa  BERT-XLNet  RoBERTa-XLNet
question_asker_intent_understanding        0.871855    0.879213       0.912949
question_body_critical                     0.858024    0.861981       0.918359
question_conversational                    0.863935    0.867535       0.896275
question_expect_short_answer               0.816629    0.825880       0.864973
question_fact_seeking                      0.833641    0.835283       0.899792
question_has_commonly_accepted_answer      0.843242    0.848846       0.894227
question_interestingness_others            0.886998    0.894965       0.920563
question_interestingness_self              0.893416    0.898027       0.919321
question_multi_intent                      0.868161    0.875827       0.903692
question_not_really_a_question             0.713576    0.696380       0.777879
question_opinion_seeking                   0.858237    0.862094       0.914847
question_type_choice                       0.903615    0.917360       0.942858
question_type_compare                      0.845019    0.860399       0.883512
question_type_consequence                  0.829638    0.846036       0.868755
question_type_definition                   0.800245    0.822687       0.845944
question_type_entity                       0.810986    0.836188       0.870531
question_type_instructions                 0.947650    0.953252       0.968936
question_type_procedure                    0.855003    0.855505       0.913897
question_type_reason_explanation           0.925285    0.931462       0.950838
question_type_spelling                     0.644748    0.725926       0.744770
question_well_written                      0.860308    0.855528       0.913620
answer_helpful                             0.764367    0.739999       0.813038
answer_level_of_information                0.831735    0.824409       0.879216
answer_plausible                           0.706247    0.671656       0.767922
answer_relevance                           0.720068    0.692142       0.783333
answer_satisfaction                        0.762289    0.753483       0.824947
answer_type_instructions                   0.949408    0.952261       0.968181
answer_type_procedure                      0.860093    0.865127       0.908062
answer_type_reason_explanation             0.929471    0.931698       0.952763
answer_well_written                        0.719715    0.716294       0.792630

In [66]:
corrs_df.mean()

BERT-RoBERTa     0.832453
BERT-XLNet       0.836581
RoBERTa-XLNet    0.880554
dtype: float64