In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from losses_metrics import *
from common import *

In [2]:
train = pd.read_csv(f'data/train.csv')
y = train[TARGETS].values
ix = np.where(train.groupby("question_body")["host"].transform("count") == 1)[0]

In [3]:
oofs2 = pd.read_csv('oofs/siamese_bert_2_oofs.csv', index_col=0).values
oofs3 = pd.read_csv('oofs/siamese_bert_3_oofs.csv', index_col=0).values
oofs4 = pd.read_csv('oofs/siamese_bert_4_oofs.csv', index_col=0).values
oofs5 = pd.read_csv('oofs/siamese_bert_5_oofs.csv', index_col=0).values
oofs6 = pd.read_csv('oofs/siamese_bert_6_oofs.csv', index_col=0).values
oofs_ro1 = pd.read_csv('oofs/siamese_roberta_1_comb_oofs.csv', index_col=0).values
oofs_xl1 = pd.read_csv('oofs/siamese_xlnet_1_comb_oofs.csv', index_col=0).values
oofs_xl2 = pd.read_csv('oofs/siamese_xlnet_2_comb_oofs.csv', index_col=0).values
oofs_al1 = pd.read_csv('oofs/siamese_albert_1_comb_oofs.csv', index_col=0).values

In [4]:
get_cvs(oofs_al1, y, ix)

/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/home/robin/anaconda3/envs/GoogleQuest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1892: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


SpearmanR
CV                                                0.413008
CV unique rows                                    0.378925
CV ignoring hard targets                          0.436447
CV unique rows ignoring hard targets              0.399252
CV w rounding                                     0.441115
CV unique rows w rounding                         0.419050
CV ignoring hard targets w rounding               0.459613
CV unique rows ignoring hard targets w rounding   0.427772

In [5]:
get_cvs(oofs2, y, ix)

SpearmanR
CV                                                0.407278
CV unique rows                                    0.371782
CV ignoring hard targets                          0.431038
CV unique rows ignoring hard targets              0.392546
CV w rounding                                     0.445099
CV unique rows w rounding                         0.435179
CV ignoring hard targets w rounding               0.457188
CV unique rows ignoring hard targets w rounding   0.425629

In [6]:
get_cvs(oofs3, y, ix)

SpearmanR
CV                                                0.410318
CV unique rows                                    0.374227
CV ignoring hard targets                          0.433832
CV unique rows ignoring hard targets              0.394997
CV w rounding                                     0.444981
CV unique rows w rounding                         0.431669
CV ignoring hard targets w rounding               0.459156
CV unique rows ignoring hard targets w rounding   0.428766

In [7]:
get_cvs(oofs4, y, ix)

SpearmanR
CV                                                0.407975
CV unique rows                                    0.372431
CV ignoring hard targets                          0.431877
CV unique rows ignoring hard targets              0.393583
CV w rounding                                     0.448154
CV unique rows w rounding                         0.425383
CV ignoring hard targets w rounding               0.457686
CV unique rows ignoring hard targets w rounding   0.425498

In [8]:
get_cvs(oofs5, y, ix)

SpearmanR
CV                                                0.408816
CV unique rows                                    0.371531
CV ignoring hard targets                          0.432205
CV unique rows ignoring hard targets              0.391879
CV w rounding                                     0.447462
CV unique rows w rounding                         0.427315
CV ignoring hard targets w rounding               0.457939
CV unique rows ignoring hard targets w rounding   0.426188

In [9]:
get_cvs(oofs6, y, ix)

SpearmanR
CV                                                0.410308
CV unique rows                                    0.373700
CV ignoring hard targets                          0.433768
CV unique rows ignoring hard targets              0.394195
CV w rounding                                     0.452310
CV unique rows w rounding                         0.433089
CV ignoring hard targets w rounding               0.460036
CV unique rows ignoring hard targets w rounding   0.427359

In [10]:
opt_ds6, opt_indices6 = optimize_rounding_params(oofs6, y, False)
np.array(opt_ds6), np.array(opt_indices6)

(array([ 8,  4, 16,  8,  4, 16,  8,  4, 16]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 19]))

In [11]:
opt_ds6, opt_indices6 = optimize_rounding_params(oofs6, y, False, ix=ix)
np.array(opt_ds6), np.array(opt_indices6)

(array([ 4,  4, 16,  8,  2,  4,  8,  2,  4, 16, 16, 16, 32]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 16, 19, 21, 23, 26]))

In [12]:
get_cvs(oofs_ro1, y, ix)

SpearmanR
CV                                                0.416249
CV unique rows                                    0.382360
CV ignoring hard targets                          0.440614
CV unique rows ignoring hard targets              0.404309
CV w rounding                                     0.449898
CV unique rows w rounding                         0.428115
CV ignoring hard targets w rounding               0.470601
CV unique rows ignoring hard targets w rounding   0.443194

In [13]:
opt_ds_ro1, opt_indices_ro1 = optimize_rounding_params(oofs_ro1, y, False)
np.array(opt_ds_ro1), np.array(opt_indices_ro1)

(array([ 4,  4, 32,  4,  4,  4,  4,  4, 16, 64]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 16, 19]))

In [14]:
opt_ds_ro1, opt_indices_ro1 = optimize_rounding_params(oofs_ro1, y, False, ix=ix)
np.array(opt_ds_ro1), np.array(opt_indices_ro1)

(array([ 4,  4,  4, 64, 32,  4,  4,  4,  4,  4,  4, 16, 64,  8]),
 array([ 2,  5,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 21]))

In [15]:
get_cvs(oofs_xl1, y, ix)

SpearmanR
CV                                                0.413989
CV unique rows                                    0.376808
CV ignoring hard targets                          0.437868
CV unique rows ignoring hard targets              0.398173
CV w rounding                                     0.448000
CV unique rows w rounding                         0.423921
CV ignoring hard targets w rounding               0.467257
CV unique rows ignoring hard targets w rounding   0.439067

In [16]:
get_cvs(oofs_xl2, y, ix)

SpearmanR
CV                                                0.415561
CV unique rows                                    0.380504
CV ignoring hard targets                          0.439752
CV unique rows ignoring hard targets              0.402323
CV w rounding                                     0.446863
CV unique rows w rounding                         0.431771
CV ignoring hard targets w rounding               0.469367
CV unique rows ignoring hard targets w rounding   0.443250

In [17]:
get_cvs((oofs2+oofs3)/2, y, ix)

SpearmanR
CV                                                0.412118
CV unique rows                                    0.375994
CV ignoring hard targets                          0.435919
CV unique rows ignoring hard targets              0.396939
CV w rounding                                     0.448326
CV unique rows w rounding                         0.431571
CV ignoring hard targets w rounding               0.462058
CV unique rows ignoring hard targets w rounding   0.430824

In [18]:
get_cvs((oofs3+oofs5)/2, y, ix)

SpearmanR
CV                                                0.413033
CV unique rows                                    0.376192
CV ignoring hard targets                          0.436685
CV unique rows ignoring hard targets              0.396945
CV w rounding                                     0.455283
CV unique rows w rounding                         0.434801
CV ignoring hard targets w rounding               0.463314
CV unique rows ignoring hard targets w rounding   0.429981

In [19]:
get_cvs((oofs2+oofs5)/2, y, ix)

SpearmanR
CV                                                0.412006
CV unique rows                                    0.375443
CV ignoring hard targets                          0.435828
CV unique rows ignoring hard targets              0.396227
CV w rounding                                     0.453626
CV unique rows w rounding                         0.432675
CV ignoring hard targets w rounding               0.462489
CV unique rows ignoring hard targets w rounding   0.428766

In [20]:
get_cvs((oofs3+oofs6)/2, y, ix)

SpearmanR
CV                                                0.412990
CV unique rows                                    0.376564
CV ignoring hard targets                          0.436623
CV unique rows ignoring hard targets              0.397339
CV w rounding                                     0.455267
CV unique rows w rounding                         0.434622
CV ignoring hard targets w rounding               0.463397
CV unique rows ignoring hard targets w rounding   0.429726

In [21]:
get_cvs((oofs_ro1+oofs_xl1)/2, y, ix)

SpearmanR
CV                                                0.423084
CV unique rows                                    0.387084
CV ignoring hard targets                          0.447699
CV unique rows ignoring hard targets              0.409294
CV w rounding                                     0.459490
CV unique rows w rounding                         0.437245
CV ignoring hard targets w rounding               0.478693
CV unique rows ignoring hard targets w rounding   0.450969

In [22]:
get_cvs((oofs_ro1+oofs_xl2)/2, y, ix)

SpearmanR
CV                                                0.423610
CV unique rows                                    0.388907
CV ignoring hard targets                          0.448323
CV unique rows ignoring hard targets              0.411274
CV w rounding                                     0.459002
CV unique rows w rounding                         0.434901
CV ignoring hard targets w rounding               0.479233
CV unique rows ignoring hard targets w rounding   0.449830

In [23]:
get_cvs((oofs_xl1+oofs6)/2, y, ix)

SpearmanR
CV                                                0.422256
CV unique rows                                    0.384862
CV ignoring hard targets                          0.446461
CV unique rows ignoring hard targets              0.406397
CV w rounding                                     0.462555
CV unique rows w rounding                         0.442123
CV ignoring hard targets w rounding               0.475676
CV unique rows ignoring hard targets w rounding   0.446994

In [24]:
get_cvs((oofs_ro1+oofs6)/2, y, ix)

SpearmanR
CV                                                0.423435
CV unique rows                                    0.387722
CV ignoring hard targets                          0.447835
CV unique rows ignoring hard targets              0.409526
CV w rounding                                     0.463246
CV unique rows w rounding                         0.442005
CV ignoring hard targets w rounding               0.475874
CV unique rows ignoring hard targets w rounding   0.446068

In [25]:
get_cvs((oofs_ro1+oofs_xl1+oofs6)/3, y, ix)

SpearmanR
CV                                                0.426310
CV unique rows                                    0.389911
CV ignoring hard targets                          0.450891
CV unique rows ignoring hard targets              0.411984
CV w rounding                                     0.467891
CV unique rows w rounding                         0.448617
CV ignoring hard targets w rounding               0.480947
CV unique rows ignoring hard targets w rounding   0.450783

In [26]:
opt_ds_ens, opt_indices_ens = optimize_rounding_params((oofs_ro1+oofs_xl1+oofs6)/3, y, False)
np.array(opt_ds_ens), np.array(opt_indices_ens)

(array([ 4,  4, 32,  8,  4,  4,  8,  4,  8, 32, 16, 32]),
 array([ 2,  5,  9, 11, 12, 13, 14, 15, 16, 19, 21, 24]))

In [27]:
opt_ds_ens, opt_indices_ens = optimize_rounding_params((oofs_ro1+oofs_xl1+oofs6)/3, y, False, ix=ix)
np.array(opt_ds_ens), np.array(opt_indices_ens)

(array([ 4, 16,  4, 32, 16,  8,  2,  4,  4,  4,  4, 32, 32,  8,  4, 32]),
 array([ 2,  3,  5,  6,  9, 11, 12, 13, 14, 15, 16, 19, 22, 24, 26, 27]))

In [28]:
get_cvs((oofs_ro1+oofs_xl2+oofs6)/3, y, ix)

SpearmanR
CV                                                0.426625
CV unique rows                                    0.391047
CV ignoring hard targets                          0.451229
CV unique rows ignoring hard targets              0.413195
CV w rounding                                     0.467387
CV unique rows w rounding                         0.446829
CV ignoring hard targets w rounding               0.480662
CV unique rows ignoring hard targets w rounding   0.452020

In [29]:
get_cvs((oofs_ro1+oofs_xl2+oofs6+oofs_al1)/4, y, ix)

SpearmanR
CV                                                0.429347
CV unique rows                                    0.393868
CV ignoring hard targets                          0.454001
CV unique rows ignoring hard targets              0.415883
CV w rounding                                     0.468289
CV unique rows w rounding                         0.447073
CV ignoring hard targets w rounding               0.482600
CV unique rows ignoring hard targets w rounding   0.452884

	SpearmanR
CV	0.429112
CV unique rows	0.393685
CV ignoring hard targets	0.453767
CV unique rows ignoring hard targets	0.415706
CV w rounding	0.466640
CV unique rows w rounding	0.446133
CV ignoring hard targets w rounding	0.481780
CV unique rows ignoring hard targets w rounding	0.452305

In [30]:
get_cvs((oofs2+oofs3+oofs4+oofs5+oofs6+oofs_xl1+4*oofs_ro1)/10, y, ix)

SpearmanR
CV                                                0.425916
CV unique rows                                    0.389904
CV ignoring hard targets                          0.450572
CV unique rows ignoring hard targets              0.412018
CV w rounding                                     0.467726
CV unique rows w rounding                         0.449817
CV ignoring hard targets w rounding               0.479619
CV unique rows ignoring hard targets w rounding   0.450425

In [31]:
from scipy.stats import rankdata
def get_rank_oofs(oofs):
    rank_oofs = np.zeros_like(oofs)
    for i in range(N_TARGETS): rank_oofs[:,i] = rankdata(oofs[:,i])
    return rank_oofs

In [32]:
rounded_oofs3 = optimized_ahmet_round(oofs3, y, verbose=False)
rounded_oofs5 = optimized_ahmet_round(oofs5, y, verbose=False)

In [33]:
rank_oofs3 = get_rank_oofs(oofs3)
rank_oofs5 = get_rank_oofs(oofs5)

mins = ((oofs3+oofs5)/2).min(axis=0)
maxs = ((oofs3+oofs5)/2).min(axis=0)

rank_oofs35 = MinMaxScaler().fit_transform((rank_oofs3 + rank_oofs5)/2)
# rank_oofs35 = rank_oofs35 * (maxs - mins) + mins

get_cvs(rank_oofs35, y, ix)

SpearmanR
CV                                                0.413050
CV unique rows                                    0.376224
CV ignoring hard targets                          0.436686
CV unique rows ignoring hard targets              0.396950
CV w rounding                                     0.413050
CV unique rows w rounding                         0.376224
CV ignoring hard targets w rounding               0.436686
CV unique rows ignoring hard targets w rounding   0.396950

In [34]:
rank_oofs3 = get_rank_oofs(rounded_oofs3)
rank_oofs5 = get_rank_oofs(rounded_oofs5)

mins = ((oofs3+oofs5)/2).min(axis=0)
maxs = ((oofs3+oofs5)/2).min(axis=0)

rank_oofs35 = MinMaxScaler().fit_transform((rank_oofs3 + rank_oofs5)/2)
# rank_oofs35 = rank_oofs35 * (maxs - mins) + mins

get_cvs(rank_oofs35, y, ix)

SpearmanR
CV                                                0.447832
CV unique rows                                    0.420983
CV ignoring hard targets                          0.462404
CV unique rows ignoring hard targets              0.425411
CV w rounding                                     0.450831
CV unique rows w rounding                         0.423581
CV ignoring hard targets w rounding               0.462627
CV unique rows ignoring hard targets w rounding   0.428040

In [35]:
rank_oofs3[:,:5]

array([[4779. , 4855. , 5501.5, 2074. ,  738. ],
       [5652. , 5448. , 2444.5, 1685. , 5624. ],
       [2196. , 1023. , 2444.5, 5029. , 3672. ],
       ...,
       [1448. , 1299. , 2444.5, 3366. , 2907. ],
       [4431. , 2815. , 5846. ,  281. ,  242. ],
       [3103. , 4769. , 2444.5,  135. , 5615. ]])

In [36]:
rank_oofs5[:,:5]

array([[3982., 4341., 5095., 1156., 1194.],
       [4829., 4982., 2419.,  827., 5377.],
       [2985., 1520., 2419., 4774., 4016.],
       ...,
       [1566., 1603., 2419., 4464., 4129.],
       [4800., 3916., 5949.,   97.,  319.],
       [4219., 5286., 2419.,   68., 5563.]])

In [37]:
MinMaxScaler().fit_transform((rank_oofs3 + rank_oofs5)/2)[:,:5]

array([[0.72065844, 0.7562783 , 0.78939759, 0.26520701, 0.15856167],
       [0.86222222, 0.8578839 , 0.        , 0.2061075 , 0.90479717],
       [0.42600823, 0.20848086, 0.        , 0.8062392 , 0.63218958],
       ...,
       [0.24765432, 0.23804035, 0.        , 0.643839  , 0.57854028],
       [0.75934156, 0.55331412, 0.95442341, 0.03045518, 0.04575002],
       [0.60222222, 0.827007  , 0.        , 0.0160507 , 0.91936147]])

In [38]:
corrs = []
for i in range(N_TARGETS):
    corr = spearmanr(np.vstack((oofs6[:,i], oofs_ro1[:,i], oofs_xl2[:,i], oofs_al1[:,i])).T)[0]
    corrs.append((corr[0,1], corr[0,2], corr[0,3], corr[1,2], corr[1,3], corr[2,3]))

In [39]:
corrs_df = pd.DataFrame(corrs, index=TARGETS, 
                        columns=['BERT-RoBERTa', 'BERT-XLNet', 'BERT-ALBERT', 
                                 'RoBERTa-XLNet', 'RoBERTa-ALBERT', 'XLNet-ALBERT'])
corrs_df

BERT-RoBERTa  BERT-XLNet  BERT-ALBERT  \
question_asker_intent_understanding        0.890034    0.891340     0.896833   
question_body_critical                     0.856560    0.866456     0.894826   
question_conversational                    0.873000    0.882877     0.885898   
question_expect_short_answer               0.837686    0.840060     0.843574   
question_fact_seeking                      0.865800    0.872718     0.866923   
question_has_commonly_accepted_answer      0.865777    0.878479     0.868481   
question_interestingness_others            0.900911    0.902039     0.904734   
question_interestingness_self              0.896772    0.900065     0.906920   
question_multi_intent                      0.873396    0.883808     0.897100   
question_not_really_a_question             0.744657    0.732152     0.762368   
question_opinion_seeking                   0.886192    0.891597     0.882233   
question_type_choice                       0.926038    0.938106     0.932868   
question_type_compare                      0.858403    0.866775     0.867314   
question_type_consequence                  0.837351    0.834072     0.865665   
question_type_definition                   0.813672    0.827665     0.844181   
question_type_entity                       0.831026    0.847438     0.864020   
question_type_instructions                 0.959585    0.962542     0.961226   
question_type_procedure                    0.880509    0.880558     0.882439   
question_type_reason_explanation           0.934359    0.936544     0.937327   
question_type_spelling                     0.655307    0.696038     0.714316   
question_well_written                      0.874296    0.880811     0.876413   
answer_helpful                             0.788714    0.784416     0.747375   
answer_level_of_information                0.864996    0.861306     0.870383   
answer_plausible                           0.753047    0.740855     0.694690   
answer_relevance                           0.757064    0.752636     0.704170   
answer_satisfaction                        0.803540    0.806033     0.777647   
answer_type_instructions                   0.961803    0.963144     0.959270   
answer_type_procedure                      0.878886    0.876772     0.859474   
answer_type_reason_explanation             0.943060    0.946205     0.935996   
answer_well_written                        0.735457    0.751039     0.721647   

                                       RoBERTa-XLNet  RoBERTa-ALBERT  \
question_asker_intent_understanding         0.912949        0.872584   
question_body_critical                      0.918359        0.845252   
question_conversational                     0.896275        0.871990   
question_expect_short_answer                0.864973        0.834798   
question_fact_seeking                       0.899792        0.856318   
question_has_commonly_accepted_answer       0.894227        0.852401   
question_interestingness_others             0.920563        0.887581   
question_interestingness_self               0.919321        0.888008   
question_multi_intent                       0.903692        0.884696   
question_not_really_a_question              0.777879        0.721546   
question_opinion_seeking                    0.914847        0.872781   
question_type_choice                        0.942858        0.921602   
question_type_compare                       0.883512        0.852670   
question_type_consequence                   0.868755        0.853608   
question_type_definition                    0.845944        0.823505   
question_type_entity                        0.870531        0.843167   
question_type_instructions                  0.968936        0.956692   
question_type_procedure                     0.913897        0.878325   
question_type_reason_explanation            0.950838        0.932903   
question_type_spelling                      0.744770        0.690436   
question_well_written                       0.

In [40]:
corrs_df.mean()

BERT-RoBERTa      0.851597
BERT-XLNet        0.856485
BERT-ALBERT       0.854210
RoBERTa-XLNet     0.880554
RoBERTa-ALBERT    0.838838
XLNet-ALBERT      0.845529
dtype: float64